# This uses newer and faster docker based build system
sudo: false

language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update

  # Give composer a random tag so that we can avoid problems caused by language pack constraints
  - git tag 10.0

  # Copy dropin files into /tmp so that we can require it into composer.json used by tests
  - cp -r . /tmp/dropin-installer-repo

  # Install test run into tests/ folder using tests/composer.json
  - composer install --working-dir=./tests/

script:
  # Sanity php syntax check
  - php -d error_reporting=32767 -l src/Dropin.php

  # Sanity composer check
  - composer validate composer.json

  # Run the real tests finally
  - "phpunit tests/"
