# This uses newer and faster docker based build system
sudo: false

language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update

  - ls -lah
  # Copy dropin files into /tmp so that we can require it into composer.json used by tests
  - ln -s . /tmp/composer-dropin-repo

  - ls -lah /tmp/composer-dropin-repo

  # Install test run into tests/ folder using tests/composer.json
  - cd tests && composer install

script:
  # Sanity php syntax check
  - php -d error_reporting=32767 -l src/Dropin.php

  # Sanity composer check
  - composer validate composer.json

  # Run the real tests finally
  - "phpunit tests/"
